definitions:
  flutter_version: &flutter_version
    flutter: stable
  env_groups: &env_groups
    groups:
      - aws_credentials    
      - playstore_credentials    
  labels: &labels
    labels:
      - RELEASE
      - ${CLIENT_ID}        
  scripts:
    # Android & iOS scripts
    - &install_dependencies
      name: Install dependencies
      script: flutter packages pub get
    - &unit_tests
      name: Unit tests
      script: |
        mkdir -p test-results
        flutter test --machine > test-results/flutter.json
    - &get_assets
      name: Get assets from AWS S3 bucket
      script: |
        echo "Client ID: ${CLIENT_ID}"
        aws s3 cp s3://cmwhitelabel/assets_${CLIENT_ID}.zip $CM_BUILD_DIR/assets.zip
        unzip assets.zip -d client_assets
    - &set_image
      name: Set main image
      script: |
        rm -rf assets/hero.png
        cp -r ./client_assets/hero.png assets/hero.png
    - &set_client_id
      name: Set client id
      script: |
        cp -r ./client_assets/client.env assets/client.env
    - &set_variables
      name: Set environment variables from settings.env
      script: |

        source ./client_assets/settings.env

        # Android stuff
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $CM_ENV

        echo "CM_KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD" >> $CM_ENV
        echo "CM_KEY_PASSWORD=$CM_KEY_PASSWORD" >> $CM_ENV
        echo "CM_KEY_ALIAS=$CM_KEY_ALIAS" >> $CM_ENV
        echo "CM_KEYSTORE_PATH=$CM_KEYSTORE_PATH" >> $CM_ENV

        echo "GCLOUD_SERVICE_ACCOUNT_CREDENTIALS<<DELIMITER" >> $CM_ENV
        echo "$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS" >> $CM_ENV
        echo "DELIMITER" >> $CM_ENV

        # iOS stuff
        echo "APP_STORE_CONNECT_KEY_IDENTIFIER=$APP_STORE_CONNECT_KEY_IDENTIFIER" >> $CM_ENV
        echo "APP_STORE_CONNECT_ISSUER_ID=$APP_STORE_CONNECT_ISSUER_ID" >> $CM_ENV

        echo "BUNDLE_ID=$BUNDLE_ID" >> $CM_ENV
        echo "APP_STORE_ID=$APP_STORE_ID" >> $CM_ENV

        echo "APP_STORE_CONNECT_PRIVATE_KEY<<DELIMITER" >> $CM_ENV
        echo "$APP_STORE_CONNECT_PRIVATE_KEY" >> $CM_ENV
        echo "DELIMITER" >> $CM_ENV

        echo "CERTIFICATE_PRIVATE_KEY<<DELIMITER" >> $CM_ENV
        echo "$CERTIFICATE_PRIVATE_KEY" >> $CM_ENV
        echo "DELIMITER" >> $CM_ENV


        echo "Your new CM_ENV is:"
        cat ${CM_ENV}


    # ----- Android scripts only -----
    - &set_package_name
      name: Set Package name
      script: |
        flutter pub add change_app_package_name
        flutter pub run change_app_package_name:main $PACKAGE_NAME
    - &change_android_icons
      name: Change Android icons
      script: |
        cp -r ./client_assets/android_assets/* ./android/app/src/main/res
    - &android_code_signing
      name: Set up key.properties
      script: | 
        cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_PASSWORD
        keyAlias=$CM_KEY_ALIAS
        storeFile=$CM_KEYSTORE_PATH
        EOF         
        cat $CM_BUILD_DIR/android/key.properties
    - &build_apk
      name: Flutter build apk
      script: |
        flutter build apk --release
    - &build_aab
      name: Flutter build aab and automatic versioning
      script: |
        # BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
        BUILD_NUMBER=2
        flutter build appbundle --release \
        --build-name=1.0.$BUILD_NUMBER \
        --build-number=$BUILD_NUMBER


    # ----- iOS scripts only -----
    - &install_pods
      name: Install pods
      script: find . -name "Podfile" -execdir pod install \;
    - &ios_code_signing
      name: iOS code signing
      script: |
        keychain initialize
        app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
        keychain add-certificates
        xcode-project use-profiles
    - &build_ipa
      name: Flutter build ipa and automatic versioning
      script: |
        BUILD_NUMBER=$$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
        flutter build ipa --release \
        --build-name=1.0.$BUILD_NUMBER \
        --build-number=$BUILD_NUMBER\
        --export-options-plist=/Users/builder/export_options.plist
    - &set_bundle_id
      name: Set bundle id
      script: |
        PBXPROJ=$CM_BUILD_DIR/ios/Runner.xcodeproj/project.pbxproj
        sed -i.bak "s/\io.codemagic.whitelabel.dev/$BUNDLE_ID/g" $PBXPROJ
    - &change_ios_icons
      name: Change iOS icons
      script: |
        rm -rf ios/Runner/Assets.xcassets/AppIcon.appiconset
        cp -r ./client_assets/ios_assets ios/Runner/Assets.xcassets/

  ios_app_store_publish: &ios_app_store_publish
    app_store_connect:
      api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
  play_store_publish: &play_store_publish
    google_play:
      credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      track: $GOOGLE_PLAY_TRACK 
      submit_as_draft: true
      changes_not_sent_for_review: true
  email_publish: &email_publish
    email: 
      recipients:
        - kevin@nevercode.io
      notify:
        success: true
        failure: true
  artifacts:  
    - &ipa build/ios/ipa/*.ipa
    - &xcodelog /tmp/xcodebuild_logs/*.log
    - &flutterdrive flutter_drive.log
    - &testresults test-results/flutter.json
    - &dsym $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    - &apk build/**/outputs/**/*.apk
    - &aab build/**/outputs/**/*.aab



workflows:
  # Builds will be triggered via REST API
  ios-client-release:
    name: iOS client release
    instance_type: mac_mini_m1
    max_build_duration: 120
    <<: *labels  
    environment:
      xcode: 14.1
      cocoapods: default
      <<: *flutter_version
      <<: *env_groups
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
        BUNDLE_ID: $BUNDLE_ID
        APP_STORE_ID: $APP_STORE_ID
    scripts:
      - *get_assets
      - *set_variables
      - *install_dependencies
      - *install_pods
      - *set_bundle_id
      - *set_client_id
      - *change_ios_icons
      - *set_image
      - *ios_code_signing
      - *build_ipa
    artifacts: 
      - *ipa
      - *xcodelog
      - *testresults
    publishing:      
      <<: *ios_app_store_publish
  
  android-client-release:
    name: Android client release
    instance_type: mac_mini_m1
    max_build_duration: 120
    <<: *labels
    environment:
      <<: *flutter_version
      <<: *env_groups
      vars:
        CLIENT_ID: "004"
        GOOGLE_PLAY_TRACK: internal
    scripts:
      - *get_assets
      - *set_variables
      - *install_dependencies
      - *set_package_name
      - *set_client_id
      - *change_android_icons
      - *set_image
      # - *android_code_signing
      - *build_apk
      - *build_aab
    artifacts: 
      - *apk
      - *aab
    publishing:
      <<: *play_store_publish
